# Generated by Django 4.1.6 on 2023-08-16 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policyno', models.CharField(default='', max_length=150)),
                ('customername', models.CharField(default='', max_length=70)),
                ('lastdate', models.CharField(default='', max_length=150)),
                ('hourtime', models.CharField(default='', max_length=150)),
                ('mintime', models.CharField(default='', max_length=150)),
                ('contactno', models.CharField(default='', max_length=150)),
            ],
        ),
    ]
